# This workflow will perform a test whenever there
# is some change in code done to ensure that the changes
# are not buggy and we are getting the desired output.
name: Push to Quay.io
on:
  push:

env:
  IMAGE_NAME: hello-world-multiarch
  IMAGE_TAGS: latest
  IMAGE_REGISTRY: quay.io
  IMAGE_NAMESPACE: mayurwaghmode111

jobs:
  push-quay:
    name: Build and push image
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        install_latest: [ true, false ]

    steps:
      # Checkout push-to-registry action github repository
      - name: Checkout Push to Registry action
        uses: actions/checkout@v2
        with:
          path: "multi-arch-buildah"

      - name: Install latest podman
        if: matrix.install_latest
        run: |
          bash multi-arch-buildah/.github/install_latest_podman.sh
      
      - name: Install latest buildah
        if: matrix.install_latest
        run: |
          bash multi-arch-buildah/.github/install_latest_buildah.sh
      # Build image using Buildah action
      - name: Build Image
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.IMAGE_TAGS }}
          base-image: busybox:latest
          entrypoint: |
            bash
            -c
            echo 'hello world'
          oci: true

      # Push the image to Quay.io (Image Registry)
      - name: Push To Quay
        uses: ./multi-arch-buildah
        id: push
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAMESPACE }}
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_PWD }}
          extra-args: |
            --disable-content-trust
      - name: Echo outputs
        run: |
          echo "${{ toJSON(steps.push.outputs) }}"
